CREATE DATABASE SOCCER_TEAM_MANAGEMENT;

USE SOCCER_TEAM_MANAGEMENT;

CREATE TABLE HLV (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    NGAY_SINH DATE
);

CREATE TABLE DOI (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    HLV_ID INT UNIQUE,
    FOREIGN KEY (HLV_ID) REFERENCES HLV(ID)
);

CREATE TABLE CAU_THU (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    NGAY_SINH DATE,
    DOI_ID INT,
    FOREIGN KEY (DOI_ID) REFERENCES DOI(ID)
);

CREATE TABLE VI_TRI_CAU_THU (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VI_TRI VARCHAR(50) NOT NULL
);

CREATE TABLE TRAN_DAU (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DOI_A INT,
    DOI_B INT,
    NGAY_GIO_DAU DATETIME,
    FOREIGN KEY (DOI_A) REFERENCES DOI(ID),
    FOREIGN KEY (DOI_B) REFERENCES DOI(ID),
    CHECK (DOI_A != DOI_B)
);

CREATE TABLE CAU_THU_VI_TRI (
    CAU_THU_ID INT,
    VI_TRI_ID INT,
    PRIMARY KEY (CAU_THU_ID, VI_TRI_ID),
    FOREIGN KEY (CAU_THU_ID) REFERENCES CAU_THU(ID),
    FOREIGN KEY (VI_TRI_ID) REFERENCES VI_TRI_CAU_THU(ID)
);

CREATE TABLE TRAN_DAU_CAU_THU (
    TRAN_DAU_ID INT,
    CAU_THU_ID INT,
    PRIMARY KEY (TRAN_DAU_ID, CAU_THU_ID),
    FOREIGN KEY (CAU_THU_ID) REFERENCES CAU_THU(ID),
    FOREIGN KEY (TRAN_DAU_ID) REFERENCES TRAN_DAU(ID)
);
