CREATE DATABASE SCHOOL_MANAGEMENT;

USE SCHOOL_MANAGEMENT;

CREATE TABLE GIAO_VIEN (
	 id INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL
);

CREATE TABLE HOC_SINH (
	id INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    giao_vien_id INT,
    FOREIGN KEY (giao_vien_id) REFERENCES GIAO_VIEN(id)
);